# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for Shadow Windows application."""

a = Analysis(
    ["shadow_entry.py"],
    pathex=["."],
    binaries=[],
    datas=[
        ("shadow/assets/Inter-Regular.ttf", "shadow/assets"),
    ],
    hiddenimports=[
        "keyboard",
        "pystray",
        "pystray._win32",
        "PIL",
        "PIL.Image",
        "PIL.ImageGrab",
        "PIL.ImageDraw",
        "PIL.ImageFont",
        "watchdog",
        "watchdog.observers",
        "watchdog.observers.read_directory_changes",
        "watchdog.observers.winapi",
        "psutil",
        "shadow",
        "shadow.__main__",
        "shadow.admin",
        "shadow.capture",
        "shadow.config",
        "shadow.controller",
        "shadow.hotkeys",
        "shadow.icons",
        "shadow.network",
        "shadow.tray",
        "shadow.ui",
        "shadow.watcher",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="Shadow",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    uac_admin=True,
)
